module.exports = [
  'node_modules/',
  'e2e',
  '__mocks__',
  'coverage',
  'functions',
  '_templates',
  '.eslintrc.js',
  'babel.config.js',
  'metro.config.js',
  'jest.config.js',
  'index.js',
  'ignoreWarnings.js',
  'dist',
];
