module.exports = {
  '@typescript-eslint/ban-ts-comment': 'off',
  '@typescript-eslint/member-delimiter-style': 0,
  '@typescript-eslint/no-empty-function': 0,
  '@typescript-eslint/no-explicit-any': 0,
  'import/prefer-default-export': 0,
  'import/no-named-as-default': 0,
  'import/no-unresolved': 0,
  'import/no-extraneous-dependencies': 0,
  'import/extensions': 0,
  'import/order': [
    'error',
    {
      pathGroups: [
        {
          pattern: 'react',
          group: 'external',
          position: 'before',
        },
        {
          pattern: '~/**',
          group: 'parent',
          position: 'before',
        },
        {
          pattern: '@*/**',
          group: 'external',
          position: 'after',
        },
      ],
      pathGroupsExcludedImportTypes: ['react'],
      alphabetize: {
        order: 'asc',
        caseInsensitive: true,
      },
    },
  ],
  'sort-imports': ['error', { ignoreDeclarationSort: true }],
  'jsx-a11y/no-noninteractive-element-interactions': 'off',
  'jsx-a11y/no-static-element-interactions': 'off',
  'jsx-a11y/click-events-have-key-events': 'off',
  'jsx-a11y/no-autofocus': 'off',
  'class-methods-use-this': 0,
  'no-nested-ternary': 0,
  'consistent-return': 0,
  'array-callback-return': 0,
  'no-duplicate-imports': 'error',
  'promise/prefer-await-to-callbacks': 'error',
  'promise/prefer-await-to-then': 'error',
  '@typescript-eslint/explicit-module-boundary-types': 'off',
  '@typescript-eslint/no-non-null-assertion': 0,
};
